<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE linkset [
  <!ENTITY r "»">
  <!ENTITY l "«">

  <!ELEMENT linkset (category+)>
    <!ELEMENT category (link*)>
      <!ATTLIST category
        name        ID             #REQUIRED
        noinclude   (true|false)   "false"
      >
      <!ELEMENT link (#PCDATA)>
        <!ATTLIST link 
          id      ID      #IMPLIED
          ref     IDREF   #IMPLIED
          href    CDATA   #IMPLIED
          title   CDATA   #IMPLIED
          style   CDATA   #IMPLIED
        >
]>
<linkset>
  <category name="Technology">
    <link ref="caveat.cc"/>
    <link href="https://thepersonever.net/" title="flashes, devlogs, and javascript oh my... remember 2 clear ur cache!" style="@import url('https://thepersonever.net/pfps/notactually/roxwize.css')" class="tpelink">thepersonever!</link>
  </category>
  <category name="Art">
    <link href="https://thepersonever.net/" title="drawings, gifs, and pencils oh my... remember 2 clear ur cache!" style="@import url('https://thepersonever.net/pfps/notactually/roxwize.css')" class="tpelink">thepersonever!</link>
    <!-- sorry i have literally everything i do on tpe from horrible music to horrible drawings -->
  </category>
  <category name="Music">
    <link href="https://thepersonever.net/" title="soundfonts, disortion, and programs oh my... remember 2 clear ur cache!" style="@import url('https://thepersonever.net/pfps/notactually/roxwize.css')" class="tpelink">thepersonever!</link>
  </category>
  <category name="GeneralAndPersonal">
    <link href="http://sniper.xproot.pw/">IdioticSniper's Website</link>
    <link href="https://keyaira.com/">keyaira.com</link>
    <link href="https://ha1iiid3enz.carrd.co/" title="haidens website" style="@import url('https://fonts.googleapis.com/css2?family=Silkscreen&amp;display=swap');!{font-family:'Silkscreen';color:#cc0000;}">haiden.exe</link>
    <link href="https://caveat.cc/" id="caveat.cc">caveat.cc</link>
    <link href="https://oerrorpage.neocities.org/">oerrorpage</link>
    <link href="https://thepersonever.net/" title="blogs, images, and texts, oh my! remember 2 clear your cache!!" style="@import url('https://thepersonever.net/pfps/notactually/roxwize.css')" class="tpelink">thepersonever!</link>
  </category>
</linkset>
